# Generated by Django 3.0.6 on 2020-05-18 23:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.FileField(upload_to=accounts.models.get_photo_path),
        ),
    ]
