# Generated by Django 3.0.6 on 2020-05-19 17:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200519_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(upload_to=accounts.models.get_photo_path),
        ),
    ]
