# Generated by Django 3.0.6 on 2020-05-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200519_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[['M', 'Кун'], ['F', 'Тян']], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
