# Generated by Django 3.0.6 on 2020-05-20 00:51

import django.core.validators
from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200519_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_picture',
            field=models.ImageField(upload_to=movies.models.get_movie_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
