# Generated by Django 3.0.6 on 2020-05-20 15:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200520_0433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['season', 'number']},
        ),
        migrations.AlterField(
            model_name='episode',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_obj',
            field=models.FileField(upload_to=movies.models.get_episode_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm', 'mkv', 'flv', 'avi', 'wmv', 'mp4'])]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_picture',
            field=models.ImageField(help_text='Лучше не грузить фотографии в альбомном ориентации, околоквадратные - лучше всего', upload_to=movies.models.get_movie_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Картинка'),
        ),
    ]
