# Generated by Django 3.0.6 on 2020-05-20 21:13

import django.core.validators
from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200520_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_picture',
            field=models.ImageField(help_text='Лучше не грузить фотографии в альбомной ориентации, околоквадратные - лучше всего', upload_to=movies.models.get_movie_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Картинка'),
        ),
    ]
