# Generated by Django 3.0.6 on 2020-05-20 21:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20200519_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 20, 21, 13, 50, 917226, tzinfo=utc), verbose_name='Publication Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='discussions.Theme'),
        ),
    ]
